version: '3.7'

services:

  # Coordinating node (dedicated)
  #   Kind of load-balancer for your cluster. Formerly "client nodes".
  #   Delegates client requests to the shards on the data nodes, 
  #   collects and aggregates the results into one final result, 
  #   and sends this result back to the client.
  # Needs : heavy CPU, medium memory
  os00:
    restart: always
    image: opensearchproject/opensearch:2.2.0
    environment:
      OPENSEARCH_JAVA_OPTS: "-Xms1024m -Xmx1024m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      node.name: os00
      node.roles: ''
      discovery.seed_hosts: os00,os01,os02,os03,os04,os05,os06,os07
      cluster.initial_master_nodes: os01
      plugins.security.ssl.transport.pemkey_filepath: certificates/os00/os00.key # relative path
      plugins.security.ssl.transport.pemcert_filepath: certificates/os00/os00.pem
      plugins.security.ssl.http.pemkey_filepath: certificates/os00/os00.key
      plugins.security.ssl.http.pemcert_filepath: certificates/os00/os00.pem
      DISABLE_INSTALL_DEMO_CONFIG: "true"
      JAVA_HOME: /usr/share/opensearch/jdk
      bootstrap.memory_lock: "true" # along with the memlock settings below, disables swapping
      network.host: "0.0.0.0"
    ulimits: 
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "./opensearch.yml:/usr/share/opensearch/config/opensearch.yml"
      - "os-data0:/usr/share/opensearch/data"
      - "./certs:/usr/share/opensearch/config/certificates:ro"
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer

  # Master node (dedicated)
  #   Manages the overall operation of a cluster and keeps track of 
  #   the cluster state.
  #   Three dedicated master nodes in three different zones is the 
  #   right approach for almost all production use cases.
  #   3 dedicated master nodes in 3 different zones is the right approach,
  #   Here, we don't do that because we're on 1 machine only.
  #   Master node should not be exposed. Coordinating or ingest nodes can be.
  # Needs : low CPU, low memory
  os01:
    restart: always
    image: opensearchproject/opensearch:2.2.0
    environment:
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      node.name: os01
      node.roles: 'master'
      discovery.seed_hosts: os00,os01,os02,os03,os04,os05,os06,os07
      cluster.initial_master_nodes: os01
      plugins.security.ssl.transport.pemkey_filepath: certificates/os01/os01.key # relative path
      plugins.security.ssl.transport.pemcert_filepath: certificates/os01/os01.pem
      plugins.security.ssl.http.pemkey_filepath: certificates/os01/os01.key
      plugins.security.ssl.http.pemcert_filepath: certificates/os01/os01.pem
      DISABLE_INSTALL_DEMO_CONFIG: "true"
      JAVA_HOME: /usr/share/opensearch/jdk
      bootstrap.memory_lock: "true" # along with the memlock settings below, disables swapping
      network.host: "0.0.0.0"
    ulimits: 
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "./opensearch.yml:/usr/share/opensearch/config/opensearch.yml"
      - "os-data1:/usr/share/opensearch/data"
      - "./certs:/usr/share/opensearch/config/certificates:ro"
  

  # Ingest & Data (hot) node
  #   Ingest : Preprocesses data before storing it in the cluster.
  #   Data : Stores and searches data. Performs all data-related 
  #     operations (indexing, searching, aggregating) on local shards.
  #   It is fine to mix both because we're using only 1 server for this cluster.
  #   If you ingest a lot of data, expose a dedicated ingest node.
  # Needs : medium CPU, heavy memory, high-speed storage
  os02:
    restart: always
    image: opensearchproject/opensearch:2.2.0
    environment:
      OPENSEARCH_JAVA_OPTS: "-Xms1024m -Xmx1024m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      node.name: os02
      node.roles: 'ingest, data'
      node.attr.temp: hot
      discovery.seed_hosts: os00,os01,os02,os03,os04,os05,os06,os07
      cluster.initial_master_nodes: os01
      plugins.security.ssl.transport.pemkey_filepath: certificates/os02/os02.key # relative path
      plugins.security.ssl.transport.pemcert_filepath: certificates/os02/os02.pem
      plugins.security.ssl.http.pemkey_filepath: certificates/os02/os02.key
      plugins.security.ssl.http.pemcert_filepath: certificates/os02/os02.pem
      DISABLE_INSTALL_DEMO_CONFIG: "true"
      JAVA_HOME: /usr/share/opensearch/jdk
      bootstrap.memory_lock: "true" # along with the memlock settings below, disables swapping
      network.host: "0.0.0.0"
    ulimits: 
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "./opensearch.yml:/usr/share/opensearch/config/opensearch.yml"
      - "os-data2:/usr/share/opensearch/data"
      - "./certs:/usr/share/opensearch/config/certificates:ro"
  
  # Ingest & Data (hot) node
  #   Ingest : Preprocesses data before storing it in the cluster.
  #   Data : Stores and searches data. Performs all data-related 
  #     operations (indexing, searching, aggregating) on local shards.
  #   It is fine to mix both because we're using only 1 server for this cluster.
  #   If you ingest a lot of data, expose a dedicated ingest node.
  # Needs : medium CPU, heavy memory, high-speed storage
  os03:
    restart: always
    image: opensearchproject/opensearch:2.2.0
    environment:
      OPENSEARCH_JAVA_OPTS: "-Xms1024m -Xmx1024m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      node.name: os03
      node.roles: 'ingest, data'
      node.attr.temp: hot
      discovery.seed_hosts: os00,os01,os02,os03,os04,os05,os06,os07
      cluster.initial_master_nodes: os01
      plugins.security.ssl.transport.pemkey_filepath: certificates/os03/os03.key # relative path
      plugins.security.ssl.transport.pemcert_filepath: certificates/os03/os03.pem
      plugins.security.ssl.http.pemkey_filepath: certificates/os03/os03.key
      plugins.security.ssl.http.pemcert_filepath: certificates/os03/os03.pem
      DISABLE_INSTALL_DEMO_CONFIG: "true"
      JAVA_HOME: /usr/share/opensearch/jdk
      bootstrap.memory_lock: "true" # along with the memlock settings below, disables swapping
      network.host: "0.0.0.0"
    ulimits: 
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "./opensearch.yml:/usr/share/opensearch/config/opensearch.yml"
      - "os-data3:/usr/share/opensearch/data"
      - "./certs:/usr/share/opensearch/config/certificates:ro"
  
  # Ingest & Data (hot) node
  #   Ingest : Preprocesses data before storing it in the cluster.
  #   Data : Stores and searches data. Performs all data-related 
  #     operations (indexing, searching, aggregating) on local shards.
  #   It is fine to mix both because we're using only 1 server for this cluster.
  #   If you ingest a lot of data, expose a dedicated ingest node.
  # Needs : medium CPU, heavy memory, high-speed storage
  os04:
    restart: always
    image: opensearchproject/opensearch:2.2.0
    environment:
      OPENSEARCH_JAVA_OPTS: "-Xms1024m -Xmx1024m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      node.name: os04
      node.roles: 'ingest, data'
      node.attr.temp: hot
      discovery.seed_hosts: os00,os01,os02,os03,os04,os05,os06,os07
      cluster.initial_master_nodes: os01
      plugins.security.ssl.transport.pemkey_filepath: certificates/os04/os04.key # relative path
      plugins.security.ssl.transport.pemcert_filepath: certificates/os04/os04.pem
      plugins.security.ssl.http.pemkey_filepath: certificates/os04/os04.key
      plugins.security.ssl.http.pemcert_filepath: certificates/os04/os04.pem
      DISABLE_INSTALL_DEMO_CONFIG: "true"
      JAVA_HOME: /usr/share/opensearch/jdk
      bootstrap.memory_lock: "true" # along with the memlock settings below, disables swapping
      network.host: "0.0.0.0"
    ulimits: 
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "./opensearch.yml:/usr/share/opensearch/config/opensearch.yml"
      - "os-data4:/usr/share/opensearch/data"
      - "./certs:/usr/share/opensearch/config/certificates:ro"
  
  # Data (warm) node
  #   Ingest : Preprocesses data before storing it in the cluster.
  #   Data : Stores and searches data. Performs all data-related 
  #     operations (indexing, searching, aggregating) on local shards.
  # Needs : lower-speed CPU, heavy memory, lower-speed storage
  os05:
    restart: always
    image: opensearchproject/opensearch:2.2.0
    environment:
      OPENSEARCH_JAVA_OPTS: "-Xms1024m -Xmx1024m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      node.name: os05
      node.roles: 'data'
      node.attr.temp: warm
      discovery.seed_hosts: os00,os01,os02,os03,os04,os05,os06,os07
      cluster.initial_master_nodes: os01
      plugins.security.ssl.transport.pemkey_filepath: certificates/os05/os05.key # relative path
      plugins.security.ssl.transport.pemcert_filepath: certificates/os05/os05.pem
      plugins.security.ssl.http.pemkey_filepath: certificates/os05/os05.key
      plugins.security.ssl.http.pemcert_filepath: certificates/os05/os05.pem
      DISABLE_INSTALL_DEMO_CONFIG: "true"
      JAVA_HOME: /usr/share/opensearch/jdk
      bootstrap.memory_lock: "true" # along with the memlock settings below, disables swapping
      network.host: "0.0.0.0"
    ulimits: 
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "./opensearch.yml:/usr/share/opensearch/config/opensearch.yml"
      - "os-data5:/usr/share/opensearch/data"
      - "./certs:/usr/share/opensearch/config/certificates:ro"
  
  # Data (warm) node
  #   Ingest : Preprocesses data before storing it in the cluster.
  #   Data : Stores and searches data. Performs all data-related 
  #     operations (indexing, searching, aggregating) on local shards.
  # Needs : lower-speed CPU, heavy memory, lower-speed storage
  os06:
    restart: always
    image: opensearchproject/opensearch:2.2.0
    environment:
      OPENSEARCH_JAVA_OPTS: "-Xms1024m -Xmx1024m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      node.name: os06
      node.roles: 'data'
      node.attr.temp: warm
      discovery.seed_hosts: os00,os01,os02,os03,os04,os05,os06,os07
      cluster.initial_master_nodes: os01
      plugins.security.ssl.transport.pemkey_filepath: certificates/os06/os06.key # relative path
      plugins.security.ssl.transport.pemcert_filepath: certificates/os06/os06.pem
      plugins.security.ssl.http.pemkey_filepath: certificates/os06/os06.key
      plugins.security.ssl.http.pemcert_filepath: certificates/os06/os06.pem
      DISABLE_INSTALL_DEMO_CONFIG: "true"
      JAVA_HOME: /usr/share/opensearch/jdk
      bootstrap.memory_lock: "true" # along with the memlock settings below, disables swapping
      network.host: "0.0.0.0"
    ulimits: 
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "./opensearch.yml:/usr/share/opensearch/config/opensearch.yml"
      - "os-data6:/usr/share/opensearch/data"
      - "./certs:/usr/share/opensearch/config/certificates:ro"
  
  # Data (warm) node
  #   Ingest : Preprocesses data before storing it in the cluster.
  #   Data : Stores and searches data. Performs all data-related 
  #     operations (indexing, searching, aggregating) on local shards.
  # Needs : lower-speed CPU, heavy memory, lower-speed storage
  os07:
    restart: always
    image: opensearchproject/opensearch:2.2.0
    environment:
      OPENSEARCH_JAVA_OPTS: "-Xms1024m -Xmx1024m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      node.name: os07
      node.roles: 'data'
      node.attr.temp: warm
      discovery.seed_hosts: os00,os01,os02,os03,os04,os05,os06,os07
      cluster.initial_master_nodes: os01
      plugins.security.ssl.transport.pemkey_filepath: certificates/os07/os07.key # relative path
      plugins.security.ssl.transport.pemcert_filepath: certificates/os07/os07.pem
      plugins.security.ssl.http.pemkey_filepath: certificates/os07/os07.key
      plugins.security.ssl.http.pemcert_filepath: certificates/os07/os07.pem
      DISABLE_INSTALL_DEMO_CONFIG: "true"
      JAVA_HOME: /usr/share/opensearch/jdk
      bootstrap.memory_lock: "true" # along with the memlock settings below, disables swapping
      network.host: "0.0.0.0"
    ulimits: 
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "./opensearch.yml:/usr/share/opensearch/config/opensearch.yml"
      - "os-data7:/usr/share/opensearch/data"
      - "./certs:/usr/share/opensearch/config/certificates:ro"
  
  kibana:
    restart: always
    image: opensearchproject/opensearch-dashboards:2.2.0
    ports:
      - 5601:5601
    volumes:
      - "./certs:/usr/share/opensearch-dashboards/config/certificates:ro"
      - "./opensearch-dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml"
    environment:
      OPENSEARCH_HOSTS: '["https://os00:9200","https://os01:9200","https://os02:9200","https://os03:9200","https://os04:9200","https://os05:9200","https://os06:9200","https://os07:9200"]' # must be a string with no spaces when specified as an environment variable
      DISABLE_INSTALL_DEMO_CONFIG: "true"

volumes:
  os-data0:
  os-data1:
  os-data2:
  os-data3:
  os-data4:
  os-data5:
  os-data6:
  os-data7:
