version: '3'

services:
  etcd1:
    image: quay.io/coreos/etcd:v3.5.0
    command: >
      etcd
      --name etcd1
      --advertise-client-urls http://etcd1:2379
      --listen-client-urls http://0.0.0.0:2379
      --initial-advertise-peer-urls http://etcd1:2380
      --listen-peer-urls http://0.0.0.0:2380
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - etcd-net

networks:
  etcd-net:
    driver: bridge

