version: '3'
services:
  emqx:
    image: emqx/emqx
    container_name: emqx
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8883:8883"
      - "8084:8084"
      - "18083:18083"
      #- "1883:1883"    # MQTT
      #- "8083:8083"    # MQTT over WebSocket
      #- "18083:18083"  # Dashboard
    environment:
      #- EMQX_ALLOW_ANONYMOUS: "true"
      - EMQX_LOADED_PLUGINS="emqx_management,emqx_auth_http,emqx_dashboard"
      - EMQX_DASHBOARD__DEFAULT_USER__LOGIN=admin
      - EMQX_DASHBOARD__DEFAULT_USER__PASSWORD=admin
      - EMQX_NODE__MAX_PORTS=65535
      - EMQX_MQTT__MAX_PACKET_SIZE=16MB
