version: '3.1'

services:
  discuz: # discuz
    image: yeasy/discuz:3.4 # fastcgi
    container_name: discuz
    restart: always
    env_file:
      - .env
    environment:
      - DISCUZ_DB_HOST=${DISCUZ_DB_HOST:-db:3306}
      - DISCUZ_DB_NAME=${DISCUZ_DB_NAME:-discuz}
      - DISCUZ_DB_USER=${DISCUZ_DB_USER:-discuz}
      - DISCUZ_DB_PASSWORD=${DISCUZ_DB_PASSWORD:-dbpassword@123}
    volumes:
      - ${DISCUZ_LOCAL_PATH:-./discuz_data}:/var/www/html/data
      - ${DISCUZ_LOCAL_CONFIG:-./discuz_config}:/var/www/html/config
    depends_on:
      - db

  db: # database
    image: mysql:8
    container_name: db
    restart: always
    env_file:
      - .env
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-discuz}
      - MYSQL_USER=${MYSQL_USER:-discuz}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-dbpassword@123}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword@123}
    volumes:
      - ${MYSQL_LOCAL_PATH:-./db_data}:/var/lib/mysql
    command:
      - '--default-authentication-plugin=mysql_native_password'

  nginx:
    # default ports 80, 443 - expose mapping as needed to host
    image: nginx:1
    container_name: nginx
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:80"    # http
      - "443:443"   # https
    volumes:
      - ${DISCUZ_LOCAL_PATH:-./discuz_data}:/var/www/html
      - ${NGINX_CONF:-./nginx_conf/default.conf}:/etc/nginx/conf.d/default.conf
      - ${NGINX_SSL_CERTS:-./nginx_ssl}:/etc/ssl:ro
      - ${NGINX_LOGS:-./nginx_logs/nginx}:/var/log/nginx
    depends_on:
      - discuz
      - db

  adminer: # lightweighted mysql manage tool, bypasses nginx
     # default port 9000
     image: adminer:4-fastcgi
     container_name: adminer
     restart: unless-stopped
     depends_on:
       - db
     ports:
       - "9000:9000"

volumes:
  discuz:
  db: