version: '3'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.0
    ports:
      - "5000:5000"
    volumes:
      - ./logstash-config/:/usr/share/logstash/pipeline/
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

