version: '3'

services:
  ntp:
    image: simonrupf/chronyd:latest
    container_name: ntp
    restart: always
    privileged: true
    ports:
      - 123:123/udp
    environment:
      #- NTP_SERVERS=time.cloudflare.com
      - LOG_LEVEL=0
