version: '3.5'

services:
  mosquitto:
    container_name: mosquitto_container
    image: eclipse-mosquitto:1.6.10
    ports:
      - 28883:8883
      - 38883:1883
    networks:
      - default
    restart: unless-stopped

networks:
  default:
