graphite:
  -
    # udp: true
    pickled: true
    period: 1
    timeunit: 'SECONDS'
    prefix: 'cassandra.environment.data_center.cassandra-3_0'
    hosts:
      - host: 'graphite'
        port: 2004   # port: 2003, for non-pickled use
    predicate:
      color: "white"
      useQualifiedName: true
      patterns:
        - "^jvm.gc.*"
        - "^jvm.memory.*"
        - "^org.apache.cassandra.metrics.Client.*"
        - "^org.apache.cassandra.metrics.ClientRequest.ConditionNotMet.*"
        - "^org.apache.cassandra.metrics.ClientRequest.ContentionHistogram.*"
        - "^org.apache.cassandra.metrics.ClientRequest.Latency.*"
        - "^org.apache.cassandra.metrics.ClientRequest.Timeouts.*"
        - "^org.apache.cassandra.metrics.ClientRequest.Unavailables.*"
        - "^org.apache.cassandra.metrics.ClientRequest.UnfinishedCommit.*"
        - "^org.apache.cassandra.metrics.ClientRequestMetrics.*"
        - "^org.apache.cassandra.metrics.Table.AllMemtablesHeapSize.*"
        - "^org.apache.cassandra.metrics.Table.AllMemtablesLiveDataSize.*"
        - "^org.apache.cassandra.metrics.Table.AllMemtablesOffHeapSize.*"
        - "^org.apache.cassandra.metrics.Table.AllMemtablesOnHeapSize.*"
        - "^org.apache.cassandra.metrics.Table.AnticompactionTime.*"
        - "^org.apache.cassandra.metrics.Table.BloomFilterDiskSpaceUsed.*"
        - "^org.apache.cassandra.metrics.Table.BloomFilterFalseRatio.*"
        - "^org.apache.cassandra.metrics.Table.BloomFilterOffHeapMemoryUsed.*"
        - "^org.apache.cassandra.metrics.Table.CasCommitLatency.*"
        - "^org.apache.cassandra.metrics.Table.CasPrepareLatency.*"
        - "^org.apache.cassandra.metrics.Table.CasProposeLatency.*"
        - "^org.apache.cassandra.metrics.Table.CompressionMetadataOffHeapMemoryUsed.*"
        - "^org.apache.cassandra.metrics.Table.CompressionRatio.*"
        - "^org.apache.cassandra.metrics.Table.CoordinatorReadLatency.*"
        - "^org.apache.cassandra.metrics.Table.CoordinatorScanLatency.*"
        - "^org.apache.cassandra.metrics.Table.EstimatedColumnCountHistogram.*"
        - "^org.apache.cassandra.metrics.Table.EstimatedPartitionCount.*"
        - "^org.apache.cassandra.metrics.Table.EstimatedPartitionSizeHistogram.*"
        - "^org.apache.cassandra.metrics.Table.IndexSummaryOffHeapMemoryUsed.*"
        - "^org.apache.cassandra.metrics.Table.KeyCacheHitRate.*"
        - "^org.apache.cassandra.metrics.Table.LiveDiskSpaceUsed.*"
        - "^org.apache.cassandra.metrics.Table.LiveScannedHistogram.*"
        - "^org.apache.cassandra.metrics.Table.LiveSSTableCount.*"
        - "^org.apache.cassandra.metrics.Table.MaxPartitionSize.*"
        - "^org.apache.cassandra.metrics.Table.MeanPartitionSize.*"
        - "^org.apache.cassandra.metrics.Table.MemtableColumnsCount.*"
        - "^org.apache.cassandra.metrics.Table.MemtableLiveDataSize.*"
        - "^org.apache.cassandra.metrics.Table.MemtableOffHeapSize.*"
        - "^org.apache.cassandra.metrics.Table.MemtableOnHeapSize.*"
        - "^org.apache.cassandra.metrics.Table.PercentRepaired.*"
        - "^org.apache.cassandra.metrics.Table.RangeLatency.*"
        - "^org.apache.cassandra.metrics.Table.ReadLatency.*"
        - "^org.apache.cassandra.metrics.Table.RowCacheHit.*"
        - "^org.apache.cassandra.metrics.Table.RowCacheMiss.*"
        - "^org.apache.cassandra.metrics.Table.SSTablesPerReadHistogram.*"
        - "^org.apache.cassandra.metrics.Table.SyncTime.*"
        - "^org.apache.cassandra.metrics.Table.TombstoneScannedHistogram.*"
        - "^org.apache.cassandra.metrics.Table.TotalDiskSpaceUsed.*"
        - "^org.apache.cassandra.metrics.Table.TrueSnapshotsSize.*"
        - "^org.apache.cassandra.metrics.Table.ValidationTime.*"
        - "^org.apache.cassandra.metrics.Table.WriteLatency.*"
        - "^org.apache.cassandra.metrics.Table.*.PendingCompactions.*"
        - "^org.apache.cassandra.metrics.CommitLog.ActiveTasks.*"
        - "^org.apache.cassandra.metrics.CommitLog.CurrentlyBlockedTask.*"
        - "^org.apache.cassandra.metrics.CommitLog.PendingTasks.*"
        - "^org.apache.cassandra.metrics.CommitLog.TotalCommitLogSize.*"
        - "^org.apache.cassandra.metrics.Compaction.BytesCompacted.*"
        - "^org.apache.cassandra.metrics.Compaction.PendingTasks.*"
        - "^org.apache.cassandra.metrics.Compaction.TotalCompactionsCompleted.*"
        - "^org.apache.cassandra.metrics.Connection.TotalTimeouts.*"
        - "^org.apache.cassandra.metrics.CQL.PreparedStatementsCount.*"
        - "^org.apache.cassandra.metrics.CQL.PreparedStatementsEvicted.*"
        - "^org.apache.cassandra.metrics.CQL.PreparedStatementsRatio.*"
        - "^org.apache.cassandra.metrics.CQL.RegularStatementsExecuted.*"
        - "^org.apache.cassandra.metrics.DroppedMessage.Dropped.*"
        - "^org.apache.cassandra.metrics.HintedHandOffManager.*"
        - "^org.apache.cassandra.metrics.ReadRepair.*"
        - "^org.apache.cassandra.metrics.Storage.Exceptions.*"
        - "^org.apache.cassandra.metrics.Storage.Load.*"
        - "^org.apache.cassandra.metrics.Storage.TotalHints.*"
        - "^org.apache.cassandra.metrics.Storage.TotalHintsInProgress.*"
        - "^org.apache.cassandra.metrics.ThreadPools.CurrentlyBlockedTasks.internal.AntiEntropyStage.*"
        - "^org.apache.cassandra.metrics.ThreadPools.PendingTasks.internal.AntiEntropyStage.*"
        - "^org.apache.cassandra.metrics.ThreadPools.ActiveTasks.internal.CompactionExecutor.*"
        - "^org.apache.cassandra.metrics.ThreadPools.CurrentlyBlockedTasks.internal.CompactionExecutor.*"
        - "^org.apache.cassandra.metrics.ThreadPools.PendingTasks.internal.CompactionExecutor.*"
        - "^org.apache.cassandra.metrics.ThreadPools.CompletedTasks.internal.GossipStage.*"
        - "^org.apache.cassandra.metrics.ThreadPools.CurrentlyBlockedTasks.internal.HintsDispatcher.*"
        - "^org.apache.cassandra.metrics.ThreadPools.PendingTasks.internal.HintsDispatcher.*"
        - "^org.apache.cassandra.metrics.ThreadPools.ActiveTasks.internal.MemtableFlushWriter.*"
        - "^org.apache.cassandra.metrics.ThreadPools.CurrentlyBlockedTasks.internal.MemtableFlushWriter.*"
        - "^org.apache.cassandra.metrics.ThreadPools.PendingTasks.internal.MemtableFlushWriter.*"
        - "^org.apache.cassandra.metrics.ThreadPools.CompletedTasks.internal.MigrationStage.*"
        - "^org.apache.cassandra.metrics.ThreadPools.CurrentlyBlockedTasks.internal.MigrationStage.*"
        - "^org.apache.cassandra.metrics.ThreadPools.PendingTasks.internal.MigrationStage.*"
        - "^org.apache.cassandra.metrics.ThreadPools.CurrentlyBlockedTasks.internal.ValidationExecutor.*"
        - "^org.apache.cassandra.metrics.ThreadPools.PendingTasks.internal.ValidationExecutor.*"
        - "^org.apache.cassandra.metrics.ThreadPools.ActiveTasks.request.MutationStage.*"
        - "^org.apache.cassandra.metrics.ThreadPools.CurrentlyBlockedTasks.request.MutationStage.*"
        - "^org.apache.cassandra.metrics.ThreadPools.PendingTasks.request.MutationStage.*"
        - "^org.apache.cassandra.metrics.ThreadPools.CurrentlyBlockedTasks.request.ReadRepairStage.*"
        - "^org.apache.cassandra.metrics.ThreadPools.PendingTasks.request.ReadRepairStage.*"
        - "^org.apache.cassandra.metrics.ThreadPools.CurrentlyBlockedTasks.request.ReadStage.*"
        - "^org.apache.cassandra.metrics.ThreadPools.PendingTasks.request.ReadStage.*"
        - "^org.apache.cassandra.metrics.ThreadPools.CurrentlyBlockedTasks.request.ReplicateOnWriteStage.*"
        - "^org.apache.cassandra.metrics.ThreadPools.PendingTasks.request.ReplicateOnWriteStage.*"
        - "^org.apache.cassandra.metrics.ThreadPools.ActiveTasks.request.RequestResponseStage.*"
        - "^org.apache.cassandra.metrics.ThreadPools.CompletedTasks.request.RequestResponseStage.*"
        - "^org.apache.cassandra.metrics.ThreadPools.CurrentlyBlockedTasks.request.RequestResponseStage.*"
        - "^org.apache.cassandra.metrics.ThreadPools.PendingTasks.request.RequestResponseStage.*"
        - "^org.apache.cassandra.metrics.ThreadPools.ActiveTasks.transport.Native-Transport-Requests.*"
        - "^org.apache.cassandra.metrics.ThreadPools.CurrentlyBlockedTasks.transport.Native-Transport-Requests.*"
        - "^org.apache.cassandra.metrics.ThreadPools.PendingTasks.transport.Native-Transport-Requests.*"
      histogram:
        color: "white"
        useQualifiedName: true
        patterns:
        - metric: ".*"
          measure: "p75|p95|max"
      timer:
        color: "white"
        useQualifiedName: true
        patterns:
        - metric: ".*"
          measure: "p75|p95|max"
        - metric: "^org.apache.cassandra.metrics.ClientRequest.Latency.*"
          measure: "m1_rate|p99"
        - metric: "^org.apache.cassandra.metrics.Table.*Latency.*"
          measure: "m1_rate"
      meter:
        color: "white"
        useQualifiedName: true
        patterns:
        - metric: "^org.apache.cassandra.metrics.ClientRequest.*"
          measure: "m1_rate"
        - metric: "^org.apache.cassandra.metrics.Compaction.TotalCompactionsCompleted.*"
          measure: "m1_rate"
        - metric: "^org.apache.cassandra.metrics.DroppedMessage.Dropped.*"
          measure: "m1_rate"
